{"frames":[{"func":"ggplot(aes(x = usd_per_hhd))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"ggplot.default(aes(x = usd_per_hhd))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"fortify(data, ...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"fortify.default(data, ...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"abort(msg)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"signal_abort(cnd)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(fallback)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class uneval.\nDid you accidentally pass `aes()` to the `data` argument?\n\u001B[90mRun `rlang::last_error()` to see where the error occurred.\u001B[39m\n"}